//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionInfo
    {
        public int id { get; set; }
        public Nullable<double> attack { get; set; }
        public Nullable<double> defense { get; set; }
        public Nullable<double> magic { get; set; }
        public Nullable<double> difficulty { get; set; }
        public int championKey { get; set; }
    }
}
