//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionStat
    {
        public int id { get; set; }
        public Nullable<double> hp { get; set; }
        public Nullable<double> hpperlevel { get; set; }
        public Nullable<double> mp { get; set; }
        public Nullable<double> mpperlevel { get; set; }
        public Nullable<double> movespeed { get; set; }
        public Nullable<double> armor { get; set; }
        public Nullable<double> armorperlevel { get; set; }
        public Nullable<double> spellblock { get; set; }
        public Nullable<double> spellblockperlevel { get; set; }
        public Nullable<double> attackrange { get; set; }
        public Nullable<double> hpregen { get; set; }
        public Nullable<double> hpregenperlevel { get; set; }
        public Nullable<double> mpregen { get; set; }
        public Nullable<double> mpregenperlevel { get; set; }
        public Nullable<double> crit { get; set; }
        public Nullable<double> critperlevel { get; set; }
        public Nullable<double> attackdamage { get; set; }
        public Nullable<double> attackdamageperlevel { get; set; }
        public Nullable<double> attackspeed { get; set; }
        public Nullable<double> attackspeedperlevel { get; set; }
        public int championKey { get; set; }
    }
}
