//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionSpell
    {
        public string id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string tooltip { get; set; }
        public Nullable<double> maxrank { get; set; }
        public string costburn { get; set; }
        public string cooldownburn { get; set; }
        public string datavalues { get; set; }
        public string vars { get; set; }
        public string costtype { get; set; }
        public string maxammo { get; set; }
        public string rangeburn { get; set; }
        public Nullable<int> image { get; set; }
        public string resource { get; set; }
        public int championKey { get; set; }
    }
}
