//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionSummary
    {
        public int key { get; set; }
        public string id { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public int image { get; set; }
        public string lore { get; set; }
        public string blurb { get; set; }
        public string partype { get; set; }
        public int passive { get; set; }
    
        public virtual ChampionImage ChampionImage { get; set; }
    }
}
