//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemGold
    {
        public int id { get; set; }
        public Nullable<int> @base { get; set; }
        public Nullable<bool> purchasable { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> sell { get; set; }
    }
}
