//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRecommendation
    {
        public int id { get; set; }
        public string champion { get; set; }
        public string title { get; set; }
        public string map { get; set; }
        public string mode { get; set; }
        public string type { get; set; }
        public string customtag { get; set; }
        public Nullable<double> sortrank { get; set; }
        public Nullable<bool> extensionpage { get; set; }
        public Nullable<bool> useobviouscheckmark { get; set; }
        public Nullable<bool> custompanel { get; set; }
        public int championKey { get; set; }
    }
}
