//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemBlock
    {
        public int id { get; set; }
        public string type { get; set; }
        public Nullable<bool> recmath { get; set; }
        public Nullable<bool> recsteps { get; set; }
        public Nullable<double> minsummonerlevel { get; set; }
        public Nullable<double> maxsummonerlevel { get; set; }
        public string showifsummonerspell { get; set; }
        public string hideifsummonerspell { get; set; }
        public string appendaftersection { get; set; }
        public int recommendationKey { get; set; }
    }
}
