//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecommendedItem
    {
        public int id { get; set; }
        public Nullable<double> count { get; set; }
        public Nullable<bool> hidecount { get; set; }
        public int blockID { get; set; }
    }
}
