//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpellEffect
    {
        public int id { get; set; }
        public Nullable<double> effect { get; set; }
        public string effectburn { get; set; }
        public int spellRankID { get; set; }
    }
}
