//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpellRank
    {
        public int id { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<double> cooldown { get; set; }
        public Nullable<double> cooldownburn { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<double> range { get; set; }
        public int spellID { get; set; }
    }
}
