//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntity : DbContext
    {
        public DatabaseEntity()
            : base("name=DatabaseEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllyTip> AllyTips { get; set; }
        public virtual DbSet<ChampionImage> ChampionImages { get; set; }
        public virtual DbSet<ChampionInfo> ChampionInfo { get; set; }
        public virtual DbSet<ChampionKey> ChampionKeys { get; set; }
        public virtual DbSet<ChampionPassive> ChampionPassives { get; set; }
        public virtual DbSet<ChampionSkin> ChampionSkins { get; set; }
        public virtual DbSet<ChampionStat> ChampionStats { get; set; }
        public virtual DbSet<ChampionSummary> ChampionSummary { get; set; }
        public virtual DbSet<ChampionType> ChampionTypes { get; set; }
        public virtual DbSet<Datatype> Datatypes { get; set; }
        public virtual DbSet<EnemyTip> EnemyTips { get; set; }
        public virtual DbSet<Hidden> Hiddens { get; set; }
        public virtual DbSet<ItemBlock> ItemBlocks { get; set; }
        public virtual DbSet<ItemRecommendation> ItemRecommendations { get; set; }
        public virtual DbSet<LevelTip> LevelTips { get; set; }
        public virtual DbSet<MapImage> MapImages { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<PassiveImage> PassiveImages { get; set; }
        public virtual DbSet<RecommendedItem> RecommendedItems { get; set; }
        public virtual DbSet<SpellEffect> SpellEffects { get; set; }
        public virtual DbSet<SpellImage> SpellImages { get; set; }
        public virtual DbSet<SpellRank> SpellRanks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Visible> Visibles { get; set; }
        public virtual DbSet<ChampionSpell> ChampionSpells { get; set; }
        public virtual DbSet<ItemEffect> ItemEffects { get; set; }
        public virtual DbSet<ItemGold> ItemGold { get; set; }
        public virtual DbSet<ItemImage> ItemImages { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemStat> ItemStats { get; set; }
        public virtual DbSet<ProfileIcon> ProfileIcons { get; set; }
    }
}
